// Generated by scripts/sync-react-charts-catalog.mjs.
// Do not edit this file directly.
import { catalogComponent } from '../../../../benchmarks/conformance/cases/119-stacked-bar-band-cursor/view'
import { createCatalogView } from '../createCatalogView'

export default createCatalogView(catalogComponent)
