// Generated by scripts/sync-react-charts-catalog.mjs.
// Do not edit this file directly.
import { catalogCase } from '../../../../benchmarks/conformance/cases/29-waterfall/tanstack'
import { createCatalogChart } from '../createCatalogChart'

export default createCatalogChart(catalogCase)
