// Generated by scripts/sync-react-charts-catalog.mjs.
// Do not edit this file directly.
import { mount as catalogCase } from '../../../../benchmarks/conformance/cases/62-ridgeline-density/tanstack'
import { createCatalogChart } from '../createCatalogChart'

export default createCatalogChart(catalogCase)
