// Generated by scripts/sync-react-charts-catalog.mjs.
// Do not edit this file directly.
import { catalogComponent } from '../../../../benchmarks/conformance/cases/80-echarts-axis-pointer/view'
import { createCatalogView } from '../createCatalogView'

export default createCatalogView(catalogComponent)
