// Generated by scripts/sync-react-charts-catalog.mjs.
// Do not edit this file directly.
import { catalogComponent } from '../../../../benchmarks/conformance/cases/81-recharts-interactive-legend/view'
import { createCatalogView } from '../createCatalogView'

export default createCatalogView(catalogComponent)
