// Generated by scripts/sync-react-charts-catalog.mjs.
// Do not edit this file directly.
import { catalogComponent } from '../../../../benchmarks/conformance/cases/83-focus-context-window/view'
import { createCatalogView } from '../createCatalogView'

export default createCatalogView(catalogComponent)
